version: 3

tasks:
  layer:build:
    desc: "Builds the layer"
    cmds:
      - docker run -d --rm --name=builder amazonlinux:2023 sleep inf
      - defer: docker stop builder
      - docker cp entrypoint.sh builder:/entrypoint.sh
      - docker exec builder bash /entrypoint.sh
      - docker cp builder:/tmp/layer/layer.zip layer.zip

  layer:publish:
    desc: "Publishes the layer"
    preconditions:
      - msg: "layer.zip not found. Run 'task layer:build' to build the layer"
        sh: "[[ -f layer.zip ]]"
      - msg: "AWS_PROFILE is not set"
        sh: "[[ -n $AWS_PROFILE ]]"
    vars:
      LAYER_NAME: openssl-lambda
      REGIONS:
        sh: |-
          aws ssm get-parameters-by-path \
            --path /aws/service/global-infrastructure/services/lambda/regions \
            --query 'Parameters[].Value' \
            --output text | tr '[:blank:]' '\n' | \
            grep -v -e ^cn- -e ^us-gov- | \
            sort -r | xargs
    cmds:
      - |-
        for region in ap-southeast-1; do
          aws lambda add-layer-version-permission --region $region --layer-name {{.LAYER_NAME}} \
            --statement-id sid1 --action lambda:GetLayerVersion --principal '*' \
            --license-info "MIT" \
            --version-number 1 \
            --zip-file fileb://layer.zip \
            --cli-read-timeout 0 \
            --cli-connect-timeout 0 \
            --compatible-runtimes python3.10 python3.11 python3.12 \
            --compatible-architectures x86_64 \
            --description "OpenSSL binaries for Amazon Linux 2023 Lambdas" \
            --query Version \
            --output text
        done
